[project]
name = "upgates"
version = "2.7.3"
dependencies = [
    "flask",
    "aiohttp",
    "schedule",
    "click",
    "pydantic",
    "logfire",
    "duckdb",
    "toml"
]

[tool.uv]
index-url = "https://pypi.org/simple"