# -*- coding: utf-8 -*-
"""
This module defines Pydantic models for parsing and validating invoice data.

Usage:

    # Example of creating an invoice item
    item = InvoiceItem(ext_kod="123", ext_kod_k=1, id="item1")

    # Example of creating an invoice
    invoice = Invoice(ext_id="inv123", id="invoice1", polozky_faktury=[item])

    # Example of creating a list of invoices
    invoices = Invoices(invoices=[invoice])

Filename: modules/abra/abra/models/abra/__init__.py
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


# Define Pydantic model for invoice parsing
class InvoiceItem(BaseModel):
    """Represents an item in the invoice."""

    ext_kod: str = Field(..., alias="ext_kod", description="External ID of the item.")
    ext_kod_k: int = Field(
        ..., alias="ext_kod_k", description="External ID item count."
    )
    id: str = Field(..., alias="id", description="Internal ID of the item.")
    last_update: Optional[datetime] = Field(
        None, description="Last update timestamp of the item."
    )
    kod: Optional[str] = Field(None, description="Item identification code.")
    ean_kod: Optional[str] = Field(None, description="EAN code of the item.")
    nazev: Optional[str] = Field(None, description="Name of the item.")
    nazev_a: Optional[str] = Field(None, description="Alternative name A of the item.")
    nazev_b: Optional[str] = Field(None, description="Alternative name B of the item.")
    nazev_c: Optional[str] = Field(None, description="Alternative name C of the item.")
    cis_rad: Optional[float] = Field(None, description="Serial number of the item.")
    typ_polozky_k: Optional[str] = Field(None, description="Type of item key.")
    baleni_id: Optional[float] = Field(None, description="Packaging ID.")
    mnoz_baleni: Optional[float] = Field(None, description="Quantity per package.")
    mnoz_mj: Optional[float] = Field(None, description="Quantity of the item.")
    typ_ceny_dph_k: Optional[str] = Field(None, description="VAT price type key.")
    typ_szb_dph_k: Optional[str] = Field(None, description="VAT rate type key.")
    szb_dph: Optional[float] = Field(None, description="VAT rate percentage.")
    cena_mj: Optional[float] = Field(None, description="Unit price of the item.")
    sleva_pol: Optional[float] = Field(None, description="Item discount.")
    upl_sleva_dokl: Optional[bool] = Field(None, description="Total document discount.")
    sum_zkl: Optional[float] = Field(None, description="Tax base amount for the item.")
    sum_dph: Optional[float] = Field(None, description="VAT amount for the item.")
    sum_celkem: Optional[float] = Field(
        None, description="Total price of the item including VAT."
    )
    sum_zkl_men: Optional[float] = Field(
        None, description="Tax base amount in foreign currency."
    )
    sum_dph_men: Optional[float] = Field(
        None, description="VAT amount in foreign currency."
    )
    sum_celkem_men: Optional[float] = Field(
        None, description="Total price including VAT in foreign currency."
    )
    objem: Optional[float] = Field(None, description="Volume of the item.")
    cen_jednotka: Optional[float] = Field(None, description="Unit price.")
    typ_vyp_ceny_k: Optional[str] = Field(
        None, description="Price calculation type key."
    )
    cena_mj_nakup: Optional[float] = Field(None, description="Purchase unit price.")
    cena_mj_prodej: Optional[float] = Field(None, description="Sales unit price.")
    cena_mj_cenik_tuz: Optional[float] = Field(
        None, description="Domestic price list unit price."
    )
    proc_zakl: Optional[float] = Field(None, description="Base percentage.")
    sleva_mnoz: Optional[float] = Field(None, description="Quantity discount.")
    zaokr_jak_k: Optional[str] = Field(None, description="Rounding method key.")
    zaokr_na_k: Optional[str] = Field(None, description="Rounding degree key.")
    sarze: Optional[str] = Field(None, description="Batch number.")
    expirace: Optional[str] = Field(None, description="Expiration date.")
    dat_trvan: Optional[str] = Field(None, description="Durability date.")
    dat_vyroby: Optional[str] = Field(None, description="Manufacturing date.")
    stav_uziv_k: Optional[str] = Field(None, description="User status key.")
    mnoz_mj_plan: Optional[float] = Field(None, description="Planned quantity.")
    mnoz_mj_real: Optional[float] = Field(None, description="Real quantity.")
    auto_zaokr: Optional[bool] = Field(None, description="Automatic rounding.")
    autogen: Optional[bool] = Field(None, description="Autogenerated.")
    poznam: Optional[str] = Field(None, description="Note.")
    sleva_dokl: Optional[float] = Field(None, description="Document discount.")
    dat_vyst: Optional[str] = Field(None, description="Issue date.")
    kop_zkl_md_ucet: Optional[bool] = Field(
        None, description="Copy base debit account."
    )
    kop_zkl_dal_ucet: Optional[bool] = Field(
        None, description="Copy base credit account."
    )
    kop_dph_md_ucet: Optional[bool] = Field(None, description="Copy VAT debit account.")
    kop_dph_dal_ucet: Optional[bool] = Field(
        None, description="Copy VAT credit account."
    )
    kop_typ_uc_op: Optional[bool] = Field(
        None, description="Copy accounting operation type."
    )
    kop_zakazku: Optional[bool] = Field(None, description="Copy project.")
    kop_stred: Optional[bool] = Field(None, description="Copy center.")
    kop_cinnost: Optional[bool] = Field(None, description="Copy activity.")
    kop_klice: Optional[bool] = Field(None, description="Copy keys.")
    kop_clen_dph: Optional[bool] = Field(None, description="Copy VAT classification.")
    kop_dat_ucto: Optional[bool] = Field(None, description="Copy accounting date.")
    dat_ucto: Optional[str] = Field(None, description="Accounting date.")
    storno: Optional[bool] = Field(
        None, description="Indicates whether the item is canceled."
    )
    storno_pol: Optional[bool] = Field(
        None, description="Indicates whether the item position is canceled."
    )
    sklad: Optional[str] = Field(None, description="Warehouse reference.")
    stredisko: Optional[str] = Field(None, description="Center.")
    cinnost: Optional[str] = Field(None, description="Activity.")
    mena: Optional[str] = Field(None, description="Currency of the item.")
    typ_uc_op: Optional[str] = Field(None, description="Accounting operation type.")
    zkl_md_ucet: Optional[str] = Field(None, description="Base debit account.")
    zkl_dal_ucet: Optional[str] = Field(None, description="Base credit account.")
    dph_md_ucet: Optional[str] = Field(None, description="VAT debit account.")
    dph_dal_ucet: Optional[str] = Field(None, description="VAT credit account.")
    zakazka: Optional[str] = Field(None, description="Project reference.")
    dodavatel: Optional[str] = Field(None, description="Supplier reference.")
    clen_dph: Optional[str] = Field(None, description="Tax classification code.")
    dph_pren: Optional[str] = Field(None, description="VAT transfer.")
    cenik: Optional[str] = Field(None, description="Price list.")
    cen_hlad: Optional[str] = Field(None, description="Price level.")
    mj: Optional[str] = Field(None, description="Unit of measure.")
    mj_objem: Optional[str] = Field(None, description="Unit of measure for volume.")
    sazba_dph: Optional[str] = Field(None, description="VAT rate key.")
    sazba_dph_puv: Optional[str] = Field(None, description="Original VAT rate key.")
    vyrobni_cisla_ok: Optional[bool] = Field(None, description="Production numbers OK.")
    id_pol_obch_zdroj: Optional[str] = Field(
        None, description="Source business item ID."
    )
    skup_plneni: Optional[str] = Field(None, description="Fulfillment group.")
    stitky: Optional[str] = Field(None, description="Tags associated with the item.")
    source: Optional[str] = Field(None, description="Source.")
    clen_kon_vyk_dph: Optional[str] = Field(
        None, description="VAT performance classification."
    )
    kop_clen_kon_vyk_dph: Optional[bool] = Field(
        None, description="Copy VAT performance classification."
    )
    ciselny_kod_zbozi: Optional[str] = Field(None, description="Commodity code.")
    druh_zbozi: Optional[str] = Field(None, description="Type of goods.")
    dokl_fak: Optional[str] = Field(None, description="Invoice document.")
    poplatek_parent_pol_fak: Optional[str] = Field(
        None, description="Parent fee invoice item."
    )
    zdroj_pro_skl: Optional[str] = Field(None, description="Source for warehouse.")
    zaloha: Optional[bool] = Field(None, description="Advance payment.")
    prodejka: Optional[bool] = Field(None, description="Sales slip.")
    vyrobni_cisla_prijata: Optional[str] = Field(
        None, description="Received production numbers."
    )
    vyrobni_cisla_vydana: Optional[str] = Field(
        None, description="Issued production numbers."
    )


class Invoice(BaseModel):
    """Represents an issued invoice with its details."""

    ext_id: str = Field(..., alias="ext_id", description="External ID of the invoice.")
    id: str = Field(..., alias="id", description="Internal ID of the invoice.")
    last_update: Optional[datetime] = Field(
        None, description="Last update timestamp of the invoice."
    )
    kod: Optional[str] = Field(None, description="Invoice identification code.")
    zamek_k: Optional[str] = Field(
        None, description="Lock status of the invoice (Open, Viewed, Locked, etc.)."
    )
    cis_dosle: Optional[str] = Field(None, description="Incoming invoice number.")
    var_sym: Optional[str] = Field(None, description="Variable symbol of the invoice.")
    cis_sml: Optional[str] = Field(None, description="Agreement number.")
    cis_obj: Optional[str] = Field(None, description="Order number.")
    dat_vyst: Optional[datetime] = Field(None, description="Issue date of the invoice.")
    duzp_puv: Optional[datetime] = Field(None, description="Taxable supply date.")
    duzp_ucto: Optional[datetime] = Field(
        None, description="Accounting taxable supply date."
    )
    dat_splat: Optional[datetime] = Field(None, description="Due date of the invoice.")
    dat_uhr: Optional[datetime] = Field(
        None, description="Settlement date of the invoice."
    )
    dat_termin: Optional[datetime] = Field(
        None, description="Term date of the invoice."
    )
    dat_real: Optional[datetime] = Field(
        None, description="Realization date of the invoice."
    )
    dat_sazby_dph: Optional[datetime] = Field(None, description="VAT rate date.")
    popis: Optional[str] = Field(None, description="Description of the invoice.")
    poznam: Optional[str] = Field(None, description="Note of the invoice.")
    uvod_txt: Optional[str] = Field(
        None, description="Introductory text of the invoice."
    )
    zav_txt: Optional[str] = Field(None, description="Closing text of the invoice.")
    sum_osv: Optional[float] = Field(None, description="Exempt amount.")
    sum_zkl_sniz: Optional[float] = Field(None, description="Reduced tax base amount.")
    sum_zkl_sniz2: Optional[float] = Field(
        None, description="Second reduced tax base amount."
    )
    sum_zkl_zakl: Optional[float] = Field(None, description="Basic tax base amount.")
    sum_zkl_celkem: Optional[float] = Field(None, description="Total tax base amount.")
    sum_dph_sniz: Optional[float] = Field(None, description="Reduced VAT amount.")
    sum_dph_sniz2: Optional[float] = Field(
        None, description="Second reduced VAT amount."
    )
    sum_dph_zakl: Optional[float] = Field(None, description="Basic VAT amount.")
    sum_dph_celkem: Optional[float] = Field(None, description="Total VAT amount.")
    sum_celk_sniz: Optional[float] = Field(None, description="Total reduced amount.")
    sum_celk_sniz2: Optional[float] = Field(
        None, description="Total second reduced amount."
    )
    sum_celk_zakl: Optional[float] = Field(None, description="Total basic amount.")
    sum_celkem: Optional[float] = Field(None, description="Total amount including VAT.")
    sum_osv_men: Optional[float] = Field(
        None, description="Exempt amount in foreign currency."
    )
    sum_zkl_sniz_men: Optional[float] = Field(
        None, description="Reduced tax base amount in foreign currency."
    )
    sum_zkl_sniz2_men: Optional[float] = Field(
        None, description="Second reduced tax base amount in foreign currency."
    )
    sum_zkl_zakl_men: Optional[float] = Field(
        None, description="Basic tax base amount in foreign currency."
    )
    sum_zkl_celkem_men: Optional[float] = Field(
        None, description="Total tax base amount in foreign currency."
    )
    sum_dph_zakl_men: Optional[float] = Field(
        None, description="Basic VAT amount in foreign currency."
    )
    sum_dph_sniz_men: Optional[float] = Field(
        None, description="Reduced VAT amount in foreign currency."
    )
    sum_dph_sniz2_men: Optional[float] = Field(
        None, description="Second reduced VAT amount in foreign currency."
    )
    sum_dph_celkem_men: Optional[float] = Field(
        None, description="Total VAT amount in foreign currency."
    )
    sum_celk_sniz_men: Optional[float] = Field(
        None, description="Total reduced amount in foreign currency."
    )
    sum_celk_sniz2_men: Optional[float] = Field(
        None, description="Total second reduced amount in foreign currency."
    )
    sum_celk_zakl_men: Optional[float] = Field(
        None, description="Total basic amount in foreign currency."
    )
    sum_celkem_men: Optional[float] = Field(
        None, description="Total amount including VAT in foreign currency."
    )
    sum_naklady: Optional[float] = Field(None, description="Total costs.")
    sleva_dokl: Optional[float] = Field(None, description="Invoice discount.")
    kurz: Optional[float] = Field(None, description="Exchange rate.")
    kurz_mnozstvi: Optional[float] = Field(None, description="Exchange rate quantity.")
    stav_uziv_k: Optional[str] = Field(
        None, description="User order status of the invoice."
    )
    naz_firmy: Optional[str] = Field(None, description="Company name.")
    ulice: Optional[str] = Field(None, description="Street address.")
    mesto: Optional[str] = Field(None, description="City.")
    psc: Optional[str] = Field(None, description="Postal code.")
    ean_kod: Optional[str] = Field(None, description="EAN code.")
    ic: Optional[str] = Field(None, description="Company ID number.")
    dic: Optional[str] = Field(None, description="VAT ID number.")
    pocet_priloh: Optional[int] = Field(None, description="Number of attachments.")
    postovni_shodna: Optional[bool] = Field(
        None, description="Indicates if the postal address is the same."
    )
    fa_nazev: Optional[str] = Field(None, description="Billing name.")
    fa_nazev2: Optional[str] = Field(None, description="Second billing name.")
    fa_ulice: Optional[str] = Field(None, description="Billing street address.")
    fa_mesto: Optional[str] = Field(None, description="Billing city.")
    fa_psc: Optional[str] = Field(None, description="Billing postal code.")
    fa_ean_kod: Optional[str] = Field(None, description="Billing EAN code.")
    buc: Optional[str] = Field(None, description="Bank account number.")
    iban: Optional[str] = Field(None, description="Bank IBAN number.")
    bic: Optional[str] = Field(None, description="Bank SWIFT BIC code.")
    spec_sym: Optional[str] = Field(None, description="Specific symbol.")
    bez_polozek: Optional[bool] = Field(
        None, description="Indicates if there are no items."
    )
    ucetni: Optional[bool] = Field(
        None, description="Indicates if the invoice is accounting."
    )
    szb_dph_sniz: Optional[float] = Field(
        None, description="Reduced VAT rate percentage."
    )
    szb_dph_sniz2: Optional[float] = Field(
        None, description="Second reduced VAT rate percentage."
    )
    szb_dph_zakl: Optional[float] = Field(
        None, description="Basic VAT rate percentage."
    )
    uzp_tuzemsko: Optional[bool] = Field(
        None, description="Indicates if the invoice is domestic."
    )
    zuctovano: Optional[bool] = Field(
        None, description="Indicates if the invoice is settled."
    )
    dat_ucto: Optional[datetime] = Field(None, description="Accounting date.")
    vyloucit_saldo: Optional[bool] = Field(
        None, description="Indicates if the balance is excluded."
    )
    storno: Optional[bool] = Field(
        None, description="Indicates whether the invoice is canceled."
    )
    zaokr_jak_sum_k: Optional[str] = Field(
        None, description="Rounding method for total sum."
    )
    zaokr_na_sum_k: Optional[str] = Field(
        None, description="Rounding degree for total sum."
    )
    zaokr_jak_dph_k: Optional[str] = Field(None, description="Rounding method for VAT.")
    zaokr_na_dph_k: Optional[str] = Field(None, description="Rounding degree for VAT.")
    metoda_zaokr_dokl_k: Optional[str] = Field(
        None, description="Rounding method for document."
    )
    vytvaret_kor_pol: Optional[bool] = Field(
        None, description="Indicates if correction items should be created."
    )
    stitky: Optional[str] = Field(None, description="Tags associated with the invoice.")
    polozky_faktury: List[InvoiceItem] = Field([], description="List of invoice items.")
    typ_dokl: Optional[str] = Field(None, description="Type of document.")
    mena: Optional[str] = Field(None, description="Currency.")
    kon_sym: Optional[str] = Field(None, description="Constant symbol.")
    firma: Optional[str] = Field(None, description="Company.")
    stat: Optional[str] = Field(None, description="Country.")
    fa_stat: Optional[str] = Field(None, description="Billing country.")
    region: Optional[str] = Field(None, description="Region.")
    fa_region: Optional[str] = Field(None, description="Billing region.")
    mist_urc: Optional[str] = Field(None, description="Destination place.")
    ban_spoj_dod: Optional[str] = Field(None, description="Supplier bank connection.")
    bankovni_ucet: Optional[str] = Field(None, description="Bank account.")
    typ_dokl_ban: Optional[str] = Field(None, description="Bank document type.")
    typ_uc_op: Optional[str] = Field(None, description="Accounting operation type.")
    prim_ucet: Optional[str] = Field(None, description="Primary account.")
    proti_ucet: Optional[str] = Field(None, description="Counter account.")
    dph_zakl_ucet: Optional[str] = Field(None, description="Basic VAT account.")
    dph_sniz_ucet: Optional[str] = Field(None, description="Reduced VAT account.")
    dph_sniz2_ucet: Optional[str] = Field(
        None, description="Second reduced VAT account."
    )
    smer_kod: Optional[str] = Field(None, description="Direction code.")
    stat_dph: Optional[str] = Field(None, description="VAT country.")
    clen_dph: Optional[str] = Field(None, description="VAT classification.")
    stredisko: Optional[str] = Field(None, description="Center.")
    cinnost: Optional[str] = Field(None, description="Activity.")
    zakazka: Optional[str] = Field(None, description="Project.")
    uzivatel: Optional[str] = Field(None, description="User.")
    zodp_osoba: Optional[str] = Field(None, description="Responsible person.")
    kontakt_osoba: Optional[str] = Field(None, description="Contact person.")
    kontakt_jmeno: Optional[str] = Field(None, description="Contact name.")
    kontakt_email: Optional[str] = Field(None, description="Contact email.")
    kontakt_tel: Optional[str] = Field(None, description="Contact phone.")
    rada: Optional[str] = Field(None, description="Series.")
    forma_dopravy: Optional[str] = Field(None, description="Delivery method.")
    uuid: Optional[str] = Field(None, description="UUID.")
    source: Optional[str] = Field(None, description="Source.")
    clen_kon_vyk_dph: Optional[str] = Field(
        None, description="VAT performance classification."
    )
    dat_up1: Optional[datetime] = Field(None, description="First update date.")
    dat_up2: Optional[datetime] = Field(None, description="Second update date.")
    dat_smir: Optional[datetime] = Field(None, description="Reconciliation date.")
    dat_penale: Optional[datetime] = Field(None, description="Penalty date.")
    podpis_prik: Optional[bool] = Field(None, description="Signature required.")
    prikaz_sum: Optional[float] = Field(None, description="Order sum.")
    prikaz_sum_men: Optional[float] = Field(
        None, description="Order sum in foreign currency."
    )
    juh_sum: Optional[float] = Field(None, description="Settlement sum.")
    juh_sum_men: Optional[float] = Field(
        None, description="Settlement sum in foreign currency."
    )
    juh_dat: Optional[float] = Field(None, description="Settlement date.")
    juh_dat_men: Optional[float] = Field(
        None, description="Settlement date in foreign currency."
    )
    zbyva_uhradit: Optional[float] = Field(
        None, description="Remaining amount to be paid."
    )
    zbyva_uhradit_men: Optional[float] = Field(
        None, description="Remaining amount to be paid in foreign currency."
    )
    forma_uhrady_cis: Optional[str] = Field(None, description="Payment method.")
    stav_uhr_k: Optional[str] = Field(None, description="Payment status.")
    juh_sum_pp: Optional[float] = Field(None, description="Partial payment sum.")
    juh_sum_pp_men: Optional[float] = Field(
        None, description="Partial payment sum in foreign currency."
    )
    sum_prepl: Optional[float] = Field(None, description="Overpayment sum.")
    sum_prepl_men: Optional[float] = Field(
        None, description="Overpayment sum in foreign currency."
    )
    sum_zalohy: Optional[float] = Field(None, description="Advance payment sum.")
    sum_zalohy_men: Optional[float] = Field(
        None, description="Advance payment sum in foreign currency."
    )
    stav_odpocet_k: Optional[str] = Field(None, description="Deduction status.")
    generovat_skl: Optional[bool] = Field(None, description="Generate warehouse.")
    zaokrouhlit_po_odpoctu: Optional[bool] = Field(
        None, description="Round after deduction."
    )
    hrom_fakt: Optional[bool] = Field(None, description="Bulk invoice.")
    zdroj_pro_skl: Optional[bool] = Field(None, description="Source for warehouse.")
    prodejka: Optional[bool] = Field(None, description="Sales slip.")
    stav_mail_k: Optional[str] = Field(None, description="Mail status.")
    dobropisovano: Optional[bool] = Field(None, description="Credit noted.")
    sum_celkem_bez_zaloh: Optional[float] = Field(
        None, description="Total amount without advances."
    )
    sum_celkem_bez_zaloh_men: Optional[float] = Field(
        None, description="Total amount without advances in foreign currency."
    )
    odpoc_auto: Optional[bool] = Field(None, description="Automatic deduction.")


class Invoices(BaseModel):
    invoices: List[Invoice]


if __name__ == "__main__":
    pass

# EOF
